n1 = input('Digite um valor: ')
print('O valor é: ', n1)
print('O tipo é: ', type(n1))
print('Só tem espaços? ', n1.isspace())
print('É um número: ', n1.isnumeric())
print('É alfabetico: ', n1.isalpha())
print('É alfanumerico? ', n1.isalnum())
print('Esta em maiúsculo? ', n1.isupper())
print('Esta em minúsculo?{} ' .format(n1.islower()))
print('Esta capitalizado? {}' .format(n1.istitle()))
